name: 'Update GitOps Repo'
description: 'Update GitOps Repo with new image changes'
inputs:
  target-option:
    description: |
      string to find target line
      default is 'image'
    required: false
    default: 'image'
  image:
    description: |
      image to update
      required is true
    required: true
  committer-name:
    description: |
      Committer name
      required is false
    required: false
  committer-email:
    description: |
      Committer email address
      required is false
    required: false
  github-token:
    description: |
      Github Token
      required is true
    required: true
  gitops-repo:
    description: |
      GitOps Repo. Must be formatted as <org>/<repo>
      required is true
    required: true
  gitops-repo-path:
    description: |
      Path to clone gitops repository in the workflow
      required is false
      default is 'gitops'
    required: false
    default: 'gitops'
  gitops-repo-ref:
    description: |
      Gitops repo ref to checkout
      required is false
      default is 'main'
    required: false
    default: 'main'
  gitops-repo-file:
    description: |
      GitOps file to update. Please include the file extension and path
      required is false
      default is 'values.yaml'
    required: false
    default: 'values.yaml'
  commit-message:
    description: |
      Commit message to use
      required is false
      default is 'Update GitOps Repo'
    required: false
    default: 'Update GitOps Repo'
runs:
  using: 'composite'
  steps:
  - name: Checkout Repository
    uses: actions/checkout@v3
    with:
      repository: many-things/gitops
      ref: main
      path: gitops
      token: ${{ inputs.github-token }}

  - name: Update GitOps Repo
    uses: actions/checkout@v3
    with:
      repository: ${{ inputs.gitops-repo }}
      ref: ${{ inputs.gitops-repo-ref }}
      path: ${{ inputs.gitops-repo-path }}
      token: ${{ inputs.github-token }}

  - name: Update GitOps Repo
    run: |
      sed -i "/${{ inputs.target-option }}/s|image: .*|image: ${{ inputs.image }}|" ${{ inputs.gitops-repo-path }}/${{ inputs.gitops-repo-file }}

  - name: Commit and push changes
    run: |
      cd ${{ inputs.gitops-repo-path }}
      git config --local user.email "${{ inputs.committer-email }}"
      git config --local user.name "${{ inputs.committer-name }}"
      git add .
      git commit -m "${{ inputs.commit-message }}"
      git push
